version: '3.1'

services:

  wordpress:
    image: wordpress
    ports:
      - 9080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: wpdb
      MYSQL_USER: wp
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
